albums/urls.py
from django.urls import path

from .views import create
from .views import AlbumListView
from .views import AlbumDetailView

app_name = 'albums'

urlpatterns = [
    path('', AlbumListView.as_view(), name='list'),
    path('create/', create, name='create'),
    path('<int:pk>/detail', AlbumDetailView.as_view(), name='detail'),
]

aws_images/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('albums/', include('albums.urls') ),
    path('images/', include('images.urls') ),
]

images/urls.py
from django.urls import path

from .views import show
from .views import delete
from .views import create
from .views import update
from .views import download

from .views import search

from .views import delete_many
from .views import download_many

app_name = 'images'

urlpatterns = [
    path('create/', create, name='create'),
    path('show/<int:pk>/', show, name='show'),
    path('delete/<int:pk>', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    path('download/<int:pk>', download, name='download'),

    path('search', search, name='search'),

    path('delete/many', delete_many, name='delete_many'),
    path('download/many', download_many, name='download_many')
]

albums/models.py
from django.db import models
from django.db.models import Sum

from AWS import create_folder

class AlbumMananger(models.Manager):

    def create_by_aws(self, bucket, title, description):
        
        key = title.replace(' ', '_').lower()
        key = create_folder(bucket, key)
        
        if key:
            return self.create(title=title, description=description,
                                bucket=bucket, key=key)

class Album(models.Model):
    title = models.CharField(max_length=50, null=False, blank=False)
    description = models.TextField()
    bucket = models.CharField(max_length=100, null=False, blank=False)
    key = models.CharField(max_length=100, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    objects = AlbumMananger()

    def __str__(self):
        return self.title

    @property
    def images(self):
        return self.image_set.all()

    @property
    def size(self):
        if self.images:
            return self.images.aggregate(Sum('size'))['size__sum']
        else:
            return 0

albums/forms.py
from django.forms import ModelForm

from .models import Album

class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = ['title', 'description']

    def __init__(self, *args, **kwargs):
        super(AlbumForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({
            'class': 'form-control',
            'id': 'title',
            'placeholder': 'Título'
        })
        
        self.fields['description'].widget.attrs.update({
            'class': 'form-control',
            'id': 'description',
            'placeholder': 'Descripción'
        })

albums/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from django.conf import settings

from django.views.generic import DetailView
from django.views.generic import ListView

from .models import Album
from .forms import AlbumForm

from images.forms import UploadFileForm

class AlbumDetailView(DetailView):
    model = Album
    template_name = 'albums/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = self.get_object().title
        context['images'] = self.get_object().images
        context['form'] = UploadFileForm({
            'album_id': self.get_object().id
        })

        return context

def create(request):
    form = AlbumForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        album = Album.objects.create_by_aws(settings.BUCKET, form.cleaned_data['title'], form.cleaned_data['description'])

        return redirect('albums:list')

class AlbumListView(ListView):
    model = Album
    template_name = 'albums/list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['title'] = 'Galería'
        context['form'] = AlbumForm()

        return context

albums/templates/albums/detail.html
{% extends 'base/base.html' %}

{% block style %}
<style>
    .row-image {
        cursor: pointer;
    }
</style>
{% endblock %}

{% block content %}
{% include 'images/snippets/modal.html' %}
{% include 'images/snippets/delete.html' %}

<div class="row mt-2">
    <div class="col">
        <h4><a href="{% url 'albums:list' %}">Galería/</a>{{ object }}</h4>
    </div>
</div>

<div class="row mt-2">
    <div class="col">
        <form action="{% url 'images:search' %}" id="image-search">
            <input type="text" class="form-control" name="q" placeholder="Escriba un prefijo">
        </form>
    </div>
</div>

<hr>

<div class="row">
    <div class="col">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newImage">
            Nueva Imagen
        </button>

        <a href="{% url 'images:download_many' %}" class="btn btn-info disabled" id="download-images">
            Descargar
        </a>

        <a href="{% url 'images:delete_many' %}" class="btn btn-danger disabled" id="delete-images" >
            Eliminar
        </a>

    </div>
</div>

<div class="row mt-2">
    <div class="col-8">
        <table class="table">
            <thead>
                <tr>
                    <td>
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="check-all-images">
                        </div>
                    </td>
                    <th>Nombre</th>
                    <th>Fecha Creación</th>
                    <th>Size</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="table-images">
                {% for image in images %}
                    {% include 'images/snippets/image.html' %}
                {% endfor%}
            </tbody>
        </table>

    </div>
    <div class="col-4">
        <img src="" alt="" width="300" height="300" id="image-preview">
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
    const imagePreview = document.getElementById('image-preview');
    const imageDefault = "https://cfimagesproject.s3.us-east-2.amazonaws.com/codigofacilito.png";

    const checkAllImages = document.getElementById('check-all-images');

    const downloadImages = document.getElementById('download-images');
    const deleteImages = document.getElementById('delete-images');

    const imageSearch = document.getElementById('image-search');

    function checkInputs(){
        var images = document.querySelectorAll('input.check-images[type="checkbox"]:checked');

        if(images.length >= 2){
            downloadImages.classList.remove('disabled');
            deleteImages.classList.remove('disabled');
        } else {
            downloadImages.classList.add('disabled');
            deleteImages.classList.add('disabled');
        }
    }

    function selectRow(row){

        var imageId = row.getAttribute('image-id');
        var input = document.getElementById('image-preview-' + imageId);

        imagePreview.src = input.value;

        document.querySelectorAll('.table-active').forEach(element => {
            element.classList.remove('table-active')
        })

        row.classList.add('table-active');
        
    }

    function setDefaultImage(){
        var rows = document.getElementsByTagName('tr');

        if(rows.length >= 2 ){
            selectRow(rows[1]);
        } else {
            imagePreview.src = imageDefault;
        }
    }

    function getImagesSelected(){
        var ids = [];
        var images = document.querySelectorAll('input.check-images[type="checkbox"]:checked');

        for(var i = 0; i < images.length; i ++){
            var imageId = images[i].getAttribute('image-id');
            ids.push(imageId);
        }

        return ids
    }

    function registerEvents(){

        document.querySelectorAll('.row-image').forEach(element => {
            element.addEventListener('click', function(event){
                selectRow(this);
            })
        })

        document.querySelectorAll('.image-edit').forEach(element => {
            element.addEventListener('click', function(event){
                event.preventDefault();

                var imageId = this.getAttribute('image-id');
                var input = document.getElementById('image-input-name-' + imageId);

                var div = document.getElementById('image-name-' + imageId);

                div.style.display = 'none';
                input.setAttribute('type', 'text');
                
            });
        })

        document.querySelectorAll('.image-form').forEach(element => {
            element.addEventListener('submit', function(event){
                event.preventDefault();

                fetch(this.action, {
                    body: new FormData(this),
                    method: 'POST'
                })
                .then(response => response.json())
                .then(data => {

                    var imageId = this.getAttribute('image-id');
                    
                    var input = document.getElementById('image-input-name-' + imageId);
                    input.value = data.name;
                    input.setAttribute('type', 'hidden');

                    var div = document.getElementById('image-name-' + imageId);
                    div.innerHTML = data.name;
                    div.style.display = 'block';

                    var preview = document.getElementById('image-preview-' + imageId);
                    preview.value = data.url;

                });
            })
        })

        document.querySelectorAll('.check-images').forEach(element => {
            element.addEventListener('change', function(event){
                checkInputs();
            })
        })
    
    }

    $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget);
        var item = button[0];
        var modal = $(this);

        fetch(item.href)
        .then(response => response.json())
        .then(function(data){
            
            modal.find('#strong-name').text(data.name);
            modal.find('#delete-modal-button')[0].href = data.delete_url;
            
        });
       
    })

    checkAllImages.addEventListener('change', function(event){
        document.querySelectorAll('.check-images').forEach(element => {
            element.checked = this.checked;
        });

        checkInputs();
    });

    deleteImages.addEventListener('click', function(event){
        event.preventDefault();
        
        var ids = getImagesSelected();

        fetch(this.href, {
            method: 'POST',
            body: JSON.stringify({'ids': ids})
        })
        .then(response => response.json())
        .then(function(data){

            for(var i = 0; i < data.ids.length; i ++ ){
                var imageId = data.ids[i];
                document.getElementById("image-" + imageId).remove();
            }

            setDefaultImage();

        });

    });

    downloadImages.addEventListener('click', function(event){
        event.preventDefault();

        var ids = getImagesSelected();

        window.location.href = this.href + '?ids=' + ids;

    });

    imageSearch.addEventListener('submit', function(event){
        event.preventDefault();

        fetch(this.action + '?q=' + this.q.value)
        .then(response => response.json())
        .then(data => {

            var table = document.getElementById('table-images');
            table.innerHTML = data.images.toString().replaceAll(',', '');

            registerEvents();
            setDefaultImage();

        });

    });

    registerEvents();
    setDefaultImage();

</script>
{% endblock %}

albums/templates/albums/list.html
{% extends 'base/base.html' %}

{% block content %}
{% include 'albums/snippets/modal.html' %}

<div class="row mt-2">
    <div class="col-6">
        <h2>Galería</h2>
    </div>

    <div class="col-6 text-right">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#newAlbum">
            Nuevo Álbum
        </button>
    </div>
</div>


<div class="row mt-2">
    <div class="col">
        
        <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Título</th>
                <th scope="col">Fecha creación</th>
                <th scope="col">Items</th>
                <th scope="col">Size</th>
              </tr>
            </thead>
            <tbody>
                {% for album in object_list %}
                    <tr>    
                        <td>
                            <i class="fas fa-folder"></i>
                            <a href="{% url 'albums:detail' album.id %}">
                                {{ album.title }}
                            </a>
                        </td>
                        <td>{{ album.created_at | date:'d M Y' }}</td>
                        <td> {{ album.images.count }}</td>
                        <td>{{ album.size }} Kb</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
    </div>
</div>

{% endblock %}